// Modos = receitas declarativas. Cada modo combina movimentos por parte.
// Para adicionar/editar um modo, basta mexer aqui.

import type { ModeConfig, ModeName } from '@/games/character/types'

export const modes: Record<ModeName, ModeConfig> = {
  idle: {
    armLeft:     { pose: 'down', transform: { rotate: 0 }, anim: 'idle' },
    armRight:    { pose: 'down', transform: { rotate: 0 }, anim: 'idle' },
    eyeLeft:     { shape: { x: 1, y: 1 }, blinkAnim: true, pupilAnim: null },
    eyeRight:    { shape: { x: 1, y: 1 }, blinkAnim: true, pupilAnim: null },
    eyebrowLeft: { pose: 'default', transform: { rotate: 0, translateY: 0 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: 0, translateY: 0 } },
    mouth:       { pose: 'idle', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
  },

  happy: {
    armLeft:     { pose: 'down', transform: { rotate: 0 }, anim: 'happy' },
    armRight:    { pose: 'down', transform: { rotate: 0 }, anim: 'happy' },
    eyeLeft:     { shape: { x: 1, y: 0.7 }, blinkAnim: true, pupilAnim: null },
    eyeRight:    { shape: { x: 1, y: 0.7 }, blinkAnim: true, pupilAnim: null },
    eyebrowLeft: { pose: 'soft-arch', transform: { rotate: -10, translateY: -3 } },
    eyebrowRight:{ pose: 'soft-arch', transform: { rotate:  10, translateY: -3 } },
    mouth:       { pose: 'happy', anim: 'grin' },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0.75,
    tears:       0,
  },

  excited: {
    armLeft:     { pose: 'head-grab', transform: { rotate: 0 }, anim: 'excited-bob' },
    armRight:    { pose: 'head-grab', transform: { rotate: 0 }, anim: 'excited-bob' },
    eyeLeft:     { shape: { x: 1, y: 0.7 }, blinkAnim: false, pupilAnim: 'pupil-sparkle' },
    eyeRight:    { shape: { x: 1, y: 0.7 }, blinkAnim: false, pupilAnim: 'pupil-sparkle' },
    eyebrowLeft: { pose: 'soft-arch', transform: { rotate: -10, translateY: -3 } },
    eyebrowRight:{ pose: 'soft-arch', transform: { rotate:  10, translateY: -3 } },
    mouth:       { pose: 'happy', anim: 'grin' },
    body:        { breathe: true, anim: 'jump-loop', armsOverHead: true },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0.75,
    tears:       0,
  },

  sad: {
    armLeft:     { pose: 'down', transform: { rotate:  10 }, anim: null },
    armRight:    { pose: 'down', transform: { rotate: -10 }, anim: null },
    eyeLeft:     { shape: { x: 0.85, y: 0.85 }, blinkAnim: false, pupilAnim: null },
    eyeRight:    { shape: { x: 0.85, y: 0.85 }, blinkAnim: false, pupilAnim: null },
    eyebrowLeft: { pose: 'worried', transform: { rotate:  24, translateY: 0 } },
    eyebrowRight:{ pose: 'worried', transform: { rotate: -24, translateY: 0 } },
    mouth:       { pose: 'sad', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 0.85, scaleY: 1 } },
    blush:       0,
    tears:       0.8,
  },

  surprised: {
    armLeft:     { pose: 'head-grab', transform: { rotate: 0 }, anim: 'surprise' },
    armRight:    { pose: 'head-grab', transform: { rotate: 0 }, anim: 'surprise' },
    eyeLeft:     { shape: { x: 1.45, y: 1.45 }, blinkAnim: false, pupilAnim: null },
    eyeRight:    { shape: { x: 1.45, y: 1.45 }, blinkAnim: false, pupilAnim: null },
    eyebrowLeft: { pose: 'arched', transform: { rotate: 0, translateY: 0 } },
    eyebrowRight:{ pose: 'arched', transform: { rotate: 0, translateY: 0 } },
    mouth:       { pose: 'surprised', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: true },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
  },

  tired: {
    armLeft:     { pose: 'down', transform: { rotate:  15 }, anim: null },
    armRight:    { pose: 'down', transform: { rotate: -15 }, anim: null },
    eyeLeft:     { shape: { x: 1, y: 0.4 }, blinkAnim: false, pupilAnim: null },
    eyeRight:    { shape: { x: 1, y: 0.4 }, blinkAnim: false, pupilAnim: null },
    eyebrowLeft: { pose: 'default', transform: { rotate:  15, translateY: 2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: -15, translateY: 2 } },
    mouth:       { pose: 'tired', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0.4,
  },

  thinking: {
    armLeft:     { pose: 'down',     transform: { rotate: 0 }, anim: 'idle' },
    armRight:    { pose: 'thinking', transform: { rotate: 2 }, anim: 'thinking' },
    eyeLeft:     { shape: { x: 0.9, y: 0.9 }, blinkAnim: false, pupilAnim: null },
    eyeRight:    { shape: { x: 0.9, y: 0.9 }, blinkAnim: false, pupilAnim: null },
    eyebrowLeft: { pose: 'default', transform: { rotate: -5, translateY: -2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate:  0, translateY: -3 } },
    mouth:       { pose: 'thinking', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
  },

  sleeping: {
    armLeft:     { pose: 'down', transform: { rotate: 0 }, anim: null },
    armRight:    { pose: 'down', transform: { rotate: 0 }, anim: null },
    // sleeping força olhos fechados via composer; valores aqui são fallback
    eyeLeft:     { shape: { x: 1, y: 1 }, blinkAnim: false, pupilAnim: null },
    eyeRight:    { shape: { x: 1, y: 1 }, blinkAnim: false, pupilAnim: null },
    eyebrowLeft: { pose: 'default', transform: { rotate: 0, translateY: 2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: 0, translateY: 2 } },
    mouth:       { pose: 'idle', anim: null },
    body:        { breathe: true, anim: null, armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
  },
}

export const defaultMode: ModeName = 'idle'
