// Modos = receitas declarativas. Cada modo combina pose + transform por parte
// e define quais ciclos de animação rodam.

import type { ModeConfig, ModeName } from '@/games/character/types'

const idleSway = { amplitude: 3, durationMs: 4000 }
const happySway = { amplitude: 12, durationMs: 1400 }

export const modes: Record<ModeName, ModeConfig> = {
  idle: {
    armLeft:     { pose: 'down', transform: { rotate: 0 } },
    armRight:    { pose: 'down', transform: { rotate: 0 } },
    eyeLeft:     { shape: { x: 1, y: 1 } },
    eyeRight:    { shape: { x: 1, y: 1 } },
    eyebrowLeft: { pose: 'default', transform: { rotate: 0, translateY: 0 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: 0, translateY: 0 } },
    mouth:       { pose: 'idle' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
    cycles:      { armSway: idleSway },
  },

  happy: {
    armLeft:     { pose: 'down', transform: { rotate: 0 } },
    armRight:    { pose: 'down', transform: { rotate: 0 } },
    eyeLeft:     { shape: { x: 1, y: 0.7 } },
    eyeRight:    { shape: { x: 1, y: 0.7 } },
    eyebrowLeft: { pose: 'soft-arch', transform: { rotate: -10, translateY: -3 } },
    eyebrowRight:{ pose: 'soft-arch', transform: { rotate:  10, translateY: -3 } },
    mouth:       { pose: 'happy' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0.75,
    tears:       0,
    cycles:      { armSway: happySway, mouthGrin: { durationMs: 2400 } },
  },

  excited: {
    armLeft:     { pose: 'head-grab', transform: { rotate: 0 } },
    armRight:    { pose: 'head-grab', transform: { rotate: 0 } },
    eyeLeft:     { shape: { x: 1, y: 0.7 } },
    eyeRight:    { shape: { x: 1, y: 0.7 } },
    eyebrowLeft: { pose: 'soft-arch', transform: { rotate: -10, translateY: -3 } },
    eyebrowRight:{ pose: 'soft-arch', transform: { rotate:  10, translateY: -3 } },
    mouth:       { pose: 'happy' },
    body:        { armsOverHead: true },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0.75,
    tears:       0,
    cycles:      {
      armBob:        { amplitude: 10, durationMs: 500 },
      pupilSparkle:  { durationMs: 800 },
      mouthGrin:     { durationMs: 2400 },
      bodyJumpLoop:  true,
    },
  },

  angry: {
    armLeft:     { pose: 'down', transform: { rotate:  18 } },
    armRight:    { pose: 'down', transform: { rotate: -18 } },
    eyeLeft:     { shape: { x: 1.05, y: 0.7 } },
    eyeRight:    { shape: { x: 1.05, y: 0.7 } },
    eyebrowLeft: { pose: 'angry', transform: { rotate: 0, translateY: 4 } },
    eyebrowRight:{ pose: 'angry', transform: { rotate: 0, translateY: 4 } },
    mouth:       { pose: 'angry' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
    cycles:      {},
  },

  sad: {
    armLeft:     { pose: 'down', transform: { rotate:  10 } },
    armRight:    { pose: 'down', transform: { rotate: -10 } },
    eyeLeft:     { shape: { x: 0.85, y: 0.85 } },
    eyeRight:    { shape: { x: 0.85, y: 0.85 } },
    eyebrowLeft: { pose: 'worried', transform: { rotate:  24, translateY: 0 } },
    eyebrowRight:{ pose: 'worried', transform: { rotate: -24, translateY: 0 } },
    mouth:       { pose: 'sad' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 0.85, scaleY: 1 } },
    blush:       0,
    tears:       0.8,
    cycles:      {},
  },

  surprised: {
    armLeft:     { pose: 'head-grab', transform: { rotate: 0 } },
    armRight:    { pose: 'head-grab', transform: { rotate: 0 } },
    eyeLeft:     { shape: { x: 1.45, y: 1.45 } },
    eyeRight:    { shape: { x: 1.45, y: 1.45 } },
    eyebrowLeft: { pose: 'arched', transform: { rotate: 0, translateY: 0 } },
    eyebrowRight:{ pose: 'arched', transform: { rotate: 0, translateY: 0 } },
    mouth:       { pose: 'surprised' },
    body:        { armsOverHead: true },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
    cycles:      {},
  },

  tired: {
    armLeft:     { pose: 'down', transform: { rotate:  15 } },
    armRight:    { pose: 'down', transform: { rotate: -15 } },
    eyeLeft:     { shape: { x: 1, y: 0.4 } },
    eyeRight:    { shape: { x: 1, y: 0.4 } },
    eyebrowLeft: { pose: 'default', transform: { rotate:  15, translateY: 2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: -15, translateY: 2 } },
    mouth:       { pose: 'tired' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0.4,
    cycles:      {},
  },

  thinking: {
    armLeft:     { pose: 'down',     transform: { rotate: 0 } },
    armRight:    { pose: 'thinking', transform: { rotate: 2 } },
    eyeLeft:     { shape: { x: 0.9, y: 0.9 } },
    eyeRight:    { shape: { x: 0.9, y: 0.9 } },
    eyebrowLeft: { pose: 'default', transform: { rotate: -5, translateY: -2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate:  0, translateY: -3 } },
    mouth:       { pose: 'thinking' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
    cycles:      { thinking: { durationMs: 1000 } },
  },

  eating: {
    armLeft:     { pose: 'down', transform: { rotate:  -5 } },
    armRight:    { pose: 'down', transform: { rotate:   5 } },
    eyeLeft:     { shape: { x: 1, y: 0.55 } },
    eyeRight:    { shape: { x: 1, y: 0.55 } },
    eyebrowLeft: { pose: 'soft-arch', transform: { rotate: -8, translateY: -2 } },
    eyebrowRight:{ pose: 'soft-arch', transform: { rotate:  8, translateY: -2 } },
    mouth:       { pose: 'chewing' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0.85,
    tears:       0,
    cycles:      { chewLoop: { durationMs: 320 }, pupilSparkle: { durationMs: 1200 } },
  },

  sleeping: {
    armLeft:     { pose: 'down', transform: { rotate: 0 } },
    armRight:    { pose: 'down', transform: { rotate: 0 } },
    eyeLeft:     { shape: { x: 1, y: 1 } },
    eyeRight:    { shape: { x: 1, y: 1 } },
    eyebrowLeft: { pose: 'default', transform: { rotate: 0, translateY: 2 } },
    eyebrowRight:{ pose: 'default', transform: { rotate: 0, translateY: 2 } },
    mouth:       { pose: 'idle' },
    body:        { armsOverHead: false },
    legLeft:     { transform: { rotate: 0, translateY: 0 } },
    legRight:    { transform: { rotate: 0, translateY: 0 } },
    nose:        { transform: { scaleX: 1, scaleY: 1 } },
    blush:       0,
    tears:       0,
    cycles:      {},
  },
}

export const defaultMode: ModeName = 'idle'
